apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-instrumentation-test
spec:
  selector:
    matchLabels:
      app: auto-instrumentation-test
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-instrumentation-test
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: app
          image: springcommunity/spring-framework-petclinic
---
apiVersion: v1
kind: Service
metadata:
  name: auto-instrumentation-test
spec:
  type: NodePort
  selector:
    app: auto-instrumentation-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080